"wasp-cli wasp add" expects a URL
Otherwise, commands like the following one won't work afterwards:

```console
wasp-cli peering info
error: parse "127.0.0.1:9090/node/peers/identity": first path segment in URL cannot contain colon
```